apply plugin: 'com.android.library'

android {
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES.txt', 'META-INF/LICENSE.txt', 'META-INF/NOTICE.txt', 'META-INF/NOTICE', 'META-INF/LICENSE', 'META-INF/DEPENDENCIES', 'META-INF/notice.txt', 'META-INF/license.txt', 'META-INF/dependencies.txt', 'META-INF/LGPL2.1']
        }
    }

    namespace 'net.steppschuh.datalogger'
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'com.google.android.gms:play-services-basement:18.7.1'
    testImplementation 'com.google.android.gms:play-services-wearable:19.0.0'
    api 'androidx.appcompat:appcompat:1.7.0'
    api 'androidx.multidex:multidex:2.0.1'
    api 'com.fasterxml.jackson.core:jackson-core:2.13.5'
    api 'com.fasterxml.jackson.core:jackson-annotations:2.13.5'
    api 'com.fasterxml.jackson.core:jackson-databind:2.13.5'
    api 'com.google.android.gms:play-services-base:18.7.1'
    api 'com.google.android.gms:play-services-location:21.3.0'
    api 'com.google.android.gms:play-services-wearable:19.0.0'
    api 'com.google.firebase:firebase-analytics:22.1.2'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'
}

//apply plugin: 'com.google.gms.google-services'
